/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface StContainer {
      'shouldRender': boolean;
      'stIf': string;
    }
  }

  interface HTMLStContainerElement extends StencilComponents.StContainer, HTMLStencilElement {}

  var HTMLStContainerElement: {
    prototype: HTMLStContainerElement;
    new (): HTMLStContainerElement;
  };
  interface HTMLElementTagNameMap {
    'st-container': HTMLStContainerElement;
  }
  interface ElementTagNameMap {
    'st-container': HTMLStContainerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-container': JSXElements.StContainerAttributes;
    }
  }
  namespace JSXElements {
    export interface StContainerAttributes extends HTMLAttributes {
      'shouldRender'?: boolean;
      'stIf'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;